/**:
  ros__parameters:
    # CAMPUS-OPTIMIZED LONGITUDINAL PID PARAMETERS
    # Tuned for smooth, comfortable acceleration/deceleration
    # Pedestrian-friendly with conservative limits

    delay_compensation_time: 0.1

    enable_smooth_stop: true
    enable_overshoot_emergency: false
    enable_large_tracking_error_emergency: true
    enable_slope_compensation: false          # Default: true → Campus: false (flat campus)
    enable_keep_stopped_until_steer_convergence: true

    # state transition
    drive_state_stop_dist: 0.5
    drive_state_offset_stop_dist: 1.0
    stopping_state_stop_dist: 0.49
    stopped_state_entry_duration_time: 0.1
    stopped_state_entry_vel: 0.01
    stopped_state_entry_acc: 0.1
    emergency_state_overshoot_stop_dist: 1.5

    # drive state - PID gains
    # Slightly reduced P gain for smoother response
    kp: 0.8                                   # Default: 1.0 → Campus: 0.8 (smoother)
    ki: 0.1
    kd: 0.0
    max_out: 1.0
    min_out: -1.0
    max_p_effort: 1.0
    min_p_effort: -1.0
    max_i_effort: 0.3
    min_i_effort: -0.3
    max_d_effort: 0.0
    min_d_effort: 0.0
    lpf_vel_error_gain: 0.9
    enable_integration_at_low_speed: false
    current_vel_threshold_pid_integration: 0.5
    time_threshold_before_pid_integration: 2.0
    enable_brake_keeping_before_stop: false
    brake_keeping_acc: -0.2

    # smooth stop state
    # More gentle stopping for passenger comfort
    smooth_stop_max_strong_acc: -0.4          # Default: -0.5 → Campus: -0.4
    smooth_stop_min_strong_acc: -0.6          # Default: -0.8 → Campus: -0.6
    smooth_stop_weak_acc: -0.25               # Default: -0.3 → Campus: -0.25
    smooth_stop_weak_stop_acc: -0.6           # Default: -0.8 → Campus: -0.6
    smooth_stop_strong_stop_acc: -2.5         # Default: -3.4 → Campus: -2.5
    smooth_stop_max_fast_vel: 0.5
    smooth_stop_min_running_vel: 0.01
    smooth_stop_min_running_acc: 0.01
    smooth_stop_weak_stop_time: 0.8
    smooth_stop_weak_stop_dist: -0.3
    smooth_stop_strong_stop_dist: -0.5

    # stopped state
    stopped_vel: 0.0
    stopped_acc: -2.5                         # Default: -3.4 → Campus: -2.5

    # emergency state
    emergency_vel: 0.0
    emergency_acc: -3.0                       # Default: -5.0 → Campus: -3.0
    emergency_jerk: -2.5                      # Default: -3.0 → Campus: -2.5

    # acceleration feedback
    lpf_acc_error_gain: 0.98
    acc_feedback_gain: 0.0

    # acceleration limit
    # SIGNIFICANTLY REDUCED for campus comfort and pedestrian safety
    max_acc: 1.2                              # Default: 3.0 → Campus: 1.2 m/s² (comfortable)
    min_acc: -2.0                             # Default: -5.0 → Campus: -2.0 m/s² (gentle braking)

    # jerk limit
    # REDUCED for smooth, comfortable ride
    max_jerk: 1.0                             # Default: 2.0 → Campus: 1.0 m/s³ (smooth)
    min_jerk: -2.0                            # Default: -5.0 → Campus: -2.0 m/s³ (gentle)
    max_acc_cmd_diff: 30.0                    # Default: 50.0 → Campus: 30.0 (smoother changes)

    # slope compensation (disabled for flat campus)
    lpf_pitch_gain: 0.95
    slope_source: "raw_pitch"
    adaptive_trajectory_velocity_th: 1.0
    max_pitch_rad: 0.1
    min_pitch_rad: -0.1
