/**:
  ros__parameters:
    # CAMPUS-OPTIMIZED CROSSWALK PARAMETERS
    # Enhanced pedestrian safety for high-density campus environment
    # Conservative approach with longer safety margins

    # == basic parameters ==
    show_processing_time: false

    # == stop position parameters ==
    # Increased stop distances for better pedestrian visibility
    stop_distance_from_crosswalk: 4.0         # Default: 3.5 → Campus: 4.0 m (more space)
    stop_distance_from_object_preferred: 3.5  # Default: 3.0 → Campus: 3.5 m (safer)
    stop_distance_from_crosswalk_limit: 3.5   # Default: 3.0 → Campus: 3.5 m
    far_object_threshold: 10.0
    stop_position_threshold: 1.0

    # == ego velocity parameters ==
    min_acc_preferred: -1.0                   # Default: -1.2 → Campus: -1.0 m/s² (gentler)
    max_acc_preferred: -1.0
    min_jerk_preferred: -1.0                  # Default: -1.2 → Campus: -1.0 m/s³
    max_jerk_preferred: -1.0
    max_jerk_for_stuck_vehicle: -0.3

    # == slave parameters ==
    disable_stop_for_yield_cancel: false
    disable_yield_for_new_stopped_object: false
    timeout_no_intention_to_walk: [3.0, 0.0]  # Default: [1.0, 0.0] → Campus: [3.0, 0.0] (patient)
    timeout_ego_stop_for_yield: 2.0           # Default: 1.0 → Campus: 2.0 s (more patient)

    # == pass judge parameters ==
    # More conservative TTC/TTV margins for campus safety
    ego_pass_first_margin_y: [5.0]            # Default: [4.0] → Campus: [5.0] s (more time)
    ego_pass_first_margin_x: [0.0]
    ego_pass_first_additional_margin: 0.5
    ego_pass_later_margin_y: [15.0]           # Default: [13.0] → Campus: [15.0] s
    ego_pass_later_margin_x: [0.0]
    ego_pass_later_additional_margin: 0.5

    # Pedestrian detection thresholds
    no_relax_velocity: 0.28
    relax_velocity: 1.0
    ego_yield_query_stop_duration: 0.1
    stuck_vehicle_vel_thr: 1.0

    # == target object parameters ==
    # Detect all possible pedestrians and vulnerable users
    target_object:
      unknown: true                           # Default: true (campus: be cautious)
      bicycle: true
      motorcycle: true
      pedestrian: true

    # == target area parameters ==
    # Extended detection range for campus environment
    crosswalk_attention_range: 2.5            # Default: 2.0 → Campus: 2.5 m (wider)
    look_unknown: true
    look_bicycle: true
    look_motorcycle: true
    look_pedestrian: true

    # == occlusion parameters ==
    # Enhanced occlusion handling for campus obstacles (buildings, trees, etc.)
    occlusion:
      enable: true
      occluded_object_velocity: 1.5           # Default: 1.0 → Campus: 1.5 m/s (cautious)
      slow_down_velocity: 1.5                 # Default: 1.0 → Campus: 1.5 m/s
      time_buffer: 1.0
      min_size: 0.5                           # Default: 1.0 → Campus: 0.5 m (detect smaller)
      free_space_max: 43
      occupied_min: 2
      do_dp: true
      do_consider_lighting: false             # Campus: indoor/outdoor lighting varies
      ignore_with_traffic_light: true
      ignore_behind_predicted_objects: true
      ignore_velocity_thresholds:
        default: 0.5
        custom_labels: []

    # Occlusion detection parameters
    psi_margin: 0.25
    atti_margin: 1.0
    wheel_tread: 1.5
    right_overhang: 0.5
    left_overhang: 0.5

    # == pass judge parameters for occluded crosswalk ==
    absence_timeout: 2.0                      # Default: 2.0 (campus: patient wait)
    ego_additional_pass_margin: 1.0           # Default: 1.0 (extra margin)

    # == regulatory element filtering parameters ==
    crosswalk_with_signal_check_for_yield: false

    # == object's velocity parameters ==
    # Conservative pedestrian velocity assumptions
    stop_object_velocity_threshold: 0.25      # Default: 0.25 (pedestrian stopped)
    min_object_velocity: 1.39                 # Default: 1.39 m/s (5 km/h)
    max_object_velocity: 2.0                  # Default: not set → Campus: 2.0 m/s (7.2 km/h)

    # Intention estimation
    distance_set_for_no_intention_to_walk: [1.0, 5.0]
    timeout_set_for_no_intention_to_walk: [2.0, 1.0]  # Default: [1.0, 0.0] → Campus: [2.0, 1.0]

    # == slow down parameters ==
    # Earlier and slower approach to crosswalks
    enable_slow_down: true
    min_slow_down_velocity: 2.5               # Default: 2.78 → Campus: 2.5 m/s (9 km/h)
    max_slow_down_jerk: -1.2                  # Default: -1.5 → Campus: -1.2 m/s³ (gentler)
    max_slow_down_accel: -2.0                 # Default: -2.5 → Campus: -2.0 m/s² (smoother)
    no_relax_velocity_for_slow_down: 0.3

    # == virtual wall parameters ==
    use_virtual_wall: true
